#!/bin/bash

### BEGIN INIT INFO
# Provides:          uwsgi
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop uwsgi process(es)
# Description:       Start/stop uwsgi process(es)
### END INIT INFO

DAEMON="/usr/local/bin/uwsgi"
INIFILE="/etc/uwsgi/raynor.ini"
NAME="raynor"
PIDFILE="/tmp/raynor.pid"

. /lib/lsb/init-functions

do_start() {
    echo "Starting $NAME"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- --ini $INIFILE 2>/dev/null || return 0
}

do_stop() {
    echo "Stopping $NAME"
    start-stop-daemon --stop --quiet --signal 3 --retry 2 --exec $DAEMON
}

do_reload() {
    echo "Reloading $NAME"
    start-stop-daemon --stop --quiet --signal HUP --exec $DAEMON
}

do_status() {
    echo "Status of $NAME"
    status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_stop
        do_start
        ;;
    reload)
        do_reload
        ;;
    status)
        do_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 2
        ;;
esac
