#!/bin/bash
#
# uwsgi - this script starts and stops the uwsgi daemon
#
# chkconfig:   - 85 15
# Description:  Start/stop uwsgi process(es)

. /etc/init.d/functions

daemon="/usr/local/bin/uwsgi"
prog=$(basename $daemon)
inifile="/etc/uwsgi/raynor.ini"
name="raynor"
lockfile="/var/lock/subsys/raynor"
pidfile="/tmp/raynor.pid"

start() {
    echo "Starting $name"
    daemon $daemon --ini $inifile
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo "Stopping $name"
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    echo "Status of $name"
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_$1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 2
esac
